### ISSUE TITLE
Ignore quotes (") when correcting messages

### ISSUE THREAD

**Issue by Daksh777** [nminaya/grammar-nazi-bot#6]
![image](https://user-images.githubusercontent.com/43648146/95607996-2b14bf80-0a7a-11eb-8afe-89d7e0f15aee.png)

The bot seems to be correcting correct words that are wrapped in quotes.

**Comment by nminaya** [comment]
@Daksh777 Hi, thanks for reporting the issue.

But this issue seems to be related to **YandexSpeller API** since that API is returning that corrections.

Try setting the Algorithm to **LanguageTool API**.

Then optionally, use /intolerant command so you don't miss any correction from LanguageTool API 👍🏼

**Comment by Daksh777** [comment]
Hi @nminaya, I checked with the LanguageTool API and it worked fine but setting strictness level to intolerant also causes problems with quotes
![932](https://user-images.githubusercontent.com/43648146/95643821-5249ac00-0acf-11eb-96e7-16fbdbcfd541.png)

**Comment by nminaya** [comment]
@Daksh777 That is actually a valid correction. Is saying that you should use “ ” instead of " ".

**Comment by Daksh777** [comment]
Okay, got it. I'll close the issue.
